---
title: "R Notebook"
output: html_notebook
---

```{r Loading packages}
library(ggplot2)
library(reshape2)
library(readxl)
library(dplyr)
library(diprate)
library(tidyr)
```


### Load dataset

```{r}
DATADIR <- "~/Thesis_work/R_code/02_12_2021_panoptic_fromcorey/"
fn <- "VQU_008_CPA_3add_1tip_FLUO-8_AM_Feb_12_21_1023.txt"

fn_filepath <- file.path(DATADIR, fn)
```

```{r}
CaFlux <- read.csv(fn_filepath, 
                    sep = "\t")
names(CaFlux) <- names(CaFlux[,-1])
CaFlux <- CaFlux[,1:384]
CaFlux$Time <- rownames(CaFlux)


CaFluxm <- melt(CaFlux, id.vars= "Time",
                    value.name = "Intensity", 
                    variable.name = "Well")

dat_melt <- CaFluxm

dat_melt$row <- substr(dat_melt$Well, 1,1)
dat_melt$column <- as.numeric(substr(dat_melt$Well, 2,3))
dat_melt$Time <- as.numeric(dat_melt$Time)/1000
dat_melt$Well <- as.character(dat_melt$Well)

dat_melt$Well <- fixWellName(dat_melt$Well)

d <- addMapInfo(dat_melt, "platemap_20210211.tsv")
```


### normalize the data within each well to the starting signal intensity
```{r}
dn <- data.frame()
dn2 <- data.frame()

for(i in unique(d$Well)){
  temp <- d[d$Well == i, ]
  temp$normint <- temp$Intensity / mean(temp$Intensity[temp$Time < 10])
  temp2 <- temp[temp$Time > 41,]
  dn <- rbind(dn, temp)
  dn2 <- rbind(dn2, temp2)
  
}

#Identify outliers that may need to be removed for cleaner data
#Calculate a mean and associated standard error across technical replicates
#I copy normint column in order to perform the summarise() function twice, otherwise it will not work
dn2$normint2 <- dn2$normint[]
avgdn2 <- dn2 %>% 
          group_by(Time, cell.line, drug1, drug2) %>%
          summarise(mean = mean(normint), se = sd(normint2)/sqrt(8), n= n())
#To assess the summary statistics of the standard error (i.e. averages, measures of spread, etc.) for each time point, I normalize the se to the mean. This is necessary because the se is going to be greater with greater values of the mean.Using these summary statistics of the standard error will facilitate identifying which groups have outliers that may need to be removed for more accurate calculations. 
avgdn2$normse <- avgdn2$se[]/avgdn2$mean[]

IQR(avgdn2$normse) #== 0.007274517
IQR(avgdn2$normse) + median(avgdn2$normse) #== 0.01736424

avgdn2$selow <- avgdn2$mean - avgdn2$se
avgdn2$sehigh <- avgdn2$mean + avgdn2$se

avgdn2[avgdn2$cell.line== "SKMEL5" & avgdn2$drug2== "CPA-Ca2+" & avgdn2$Time > 50, ] %>%  
  ggplot() +
  geom_line(aes(x=Time, y=mean, color=interaction(drug1, drop=TRUE, sep='-'))) +
  theme(legend.position= "bottom", legend.title = element_text())+
  labs(x = "Time (seconds)", y = "Normalized Intensity", color= "BRAFi condition") +
  geom_ribbon(aes(x= Time, ymin= selow, ymax= sehigh, group= drug1), alpha=0.2, fill= "grey65")
```
###  Normalize wells to the max intensity of the ionomycin add, followed by stats
```{r}

dn3 <- data.frame()

for(i in unique(dn2$Well)){
  temp <- dn2[dn2$Well == i, ]
  temp$normint3 <- temp$normint / max(temp$normint[temp$Time > 550])
  dn3 <- rbind(dn3, temp)
}

dn3$normint4 <- dn3$normint3[]
avgdn3 <- dn3 %>%
    group_by(Time, cell.line, drug1, drug2) %>%
          summarise(mean = mean(normint3), se = sd(normint4)/sqrt(8), n= n())


avgdn3$normse <- avgdn3$se[]/avgdn3$mean[]

IQR(avgdn3$normse) #== 0.01706552
IQR(avgdn3$normse) + median(avgdn3$normse) #== 0.03386607

avgdn3$selow <- avgdn3$mean - avgdn3$se
avgdn3$sehigh <- avgdn3$mean + avgdn3$se
```


plotting ionomycin normalized data
```{r}

avgdn3[avgdn3$cell.line== "SKMEL5" & avgdn3$drug2== "CPA-Ca2+",] %>%  
  ggplot() +
  geom_line(aes(x=Time, y=mean, color=interaction(drug1, drop=TRUE, sep='-'))) +
  theme(legend.position= "bottom", legend.title = element_blank())+
  labs(x = "Time (seconds)", y = "Normalized Intensity") +
  geom_ribbon(aes(x= Time, ymin= selow, ymax= sehigh, group= drug1), alpha=0.2, fill= "grey65")


```
### Normalizing data to lowest point under 100 seconds which brings the beginning points of the ER release together
```{r}
m <- data.frame()

for(i in unique(dn3$Well)){
  temp <- dn3[dn3$Well == i, ]
  temp$normint7 <- temp$normint3 / min(temp$normint3[temp$Time < 100])
  temp$normint8 <- temp$normint7
  m <- rbind(m, temp)
}

avgm <- m %>%
    group_by(Time, cell.line, drug1, drug2) %>%
          summarise(mean = mean(normint7), se = sd(normint8)/sqrt(8), n= n())

avgm$selow <- avgm$mean - avgm$se
avgm$sehigh <- avgm$mean + avgm$se

#test plot data
avgm[avgm$cell.line== "SKMEL5" & avgm$drug2== "CPA-Ca2+" & avgm$Time < 540 & avgm$Time > 50 , ] %>%  
  ggplot() +
  geom_line(aes(x=Time, y=mean, color=interaction(drug1, drop=TRUE, sep='-'))) +
  theme(legend.position= "bottom", legend.title = element_text())+
  labs(x = "Time (seconds)", y = "Normalized Intensity", color= "BRAFi condition") +
  geom_ribbon(aes(x= Time, ymin= selow, ymax= sehigh, group= drug1), alpha=0.2, fill= "grey65") 
```
