---
title: "Calcium Flux Analysis"
author: "Blake Baleami"
date: "1/26/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Corey's Calcium Flux Analysis

```{r}
# load packages
library(ggplot2)
library(reshape2)
getwd()
rm(caFlux_try2_dat)
# read in data file
caFlux_try2_dat <- read.csv('../data/SingleAdd_IP3_Fluo-8_May_01_19.txt', 
                       sep = "\t")
# the last column on the sheet is a column of 'NA's
# shifts the names of the columns over by 1 to the left
names(caFlux_try2_dat) <- names(caFlux_try2_dat[,-1])
# adjusts data frame to the correct number of columns in the data frame (i.e. parses out the NA column from the data frame)
caFlux_try2_dat <- caFlux_try2_dat[,1:384]
# make the rownames a time variable in the data frame as the last column in the data frame
caFlux_try2_dat$Time <- rownames(caFlux_try2_dat)
# melts the data frame by well; defaults to using time as an id variable
caFlux_try2_melt <- melt(caFlux_try2_dat, 
                    value.name = "Intensity", 
                    variable.name = "Well")
# dividing time by 1000
caFlux_try2_melt$time <- as.numeric(caFlux_try2_melt$Time)/1000
# creating columns for the row and column of the well
caFlux_try2_melt$row <- substr(caFlux_try2_melt$Well, 1, 1)
caFlux_try2_melt$column <- substr(caFlux_try2_melt$Well, 2, 3)

# why are columns 1, 2, 23, and 24 being excluded from the data frame?? (that's what the next line of code does)
caFlux_try2_melt<-caFlux_try2_melt[!(caFlux_try2_melt$column %in% c("1","2","23","24")),]
# add an Agonist column to the data frame
caFlux_try2_melt$Agonist <- rep(c("Ionomycin", "Thapsigargin"), each = 322*5)
# add a column to specify concentration to the data frame
caFlux_try2_melt$concentration <- rep(c("High", "Medium-High", "Medium", "Medium-Low", "Low"), each = 322)
# add a column for the population the cells were in 
caFlux_try2_melt$pop <- rep(c("Untreated", "Idling"), each = 322*10)
# copy the data frame over to a test data frame
caFlux_try2_test <- caFlux_try2_melt

dn <- data.frame()

# looks like there is some normalization based on subtracting the minimum intensity
for(i in unique(caFlux_try2_test$Well)){
  # print(i)
  temp <- subset(caFlux_try2_test, caFlux_try2_test$Well==i)
  temp$normIntensity <- temp$Intensity - temp$Intensity[temp$Time == temp$Time[which.min(temp$Intensity)]]
  temp1 <- temp[which.min(temp$Intensity):length(temp$Intensity),]
  dn <- rbind(dn, temp1)
}
```

